/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AppLeagueService } from "../appLeague.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AppLeagueCreateInput } from "./AppLeagueCreateInput";
import { AppLeague } from "./AppLeague";
import { AppLeagueFindManyArgs } from "./AppLeagueFindManyArgs";
import { AppLeagueWhereUniqueInput } from "./AppLeagueWhereUniqueInput";
import { AppLeagueUpdateInput } from "./AppLeagueUpdateInput";
import { AppRoundFindManyArgs } from "../../appRound/base/AppRoundFindManyArgs";
import { AppRound } from "../../appRound/base/AppRound";
import { AppRoundWhereUniqueInput } from "../../appRound/base/AppRoundWhereUniqueInput";
import { RoundFindManyArgs } from "../../round/base/RoundFindManyArgs";
import { Round } from "../../round/base/Round";
import { RoundWhereUniqueInput } from "../../round/base/RoundWhereUniqueInput";
import { AppUserDto } from "../../appUser/AppUserDto";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AppLeagueControllerBase {
  constructor(
    protected readonly service: AppLeagueService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AppLeague })
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAppLeague(
    @common.Body() data: AppLeagueCreateInput
  ): Promise<AppLeague> {
    return await this.service.createAppLeague({
      data: data,
      select: {
        createdAt: true,
        id: true,
        isSelected: true,
        joinCode: true,
        leagueCode: true,
        leagueName: true,
        members: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AppLeague] })
  @ApiNestedQuery(AppLeagueFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appLeagues(@common.Req() request: Request): Promise<AppLeague[]> {
    const args = plainToClass(AppLeagueFindManyArgs, request.query);
    return this.service.appLeagues({
      ...args,
      select: {
        createdAt: true,
        id: true,
        isSelected: true,
        joinCode: true,
        leagueCode: true,
        leagueName: true,
        members: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AppLeague })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async appLeague(
    @common.Param() params: AppLeagueWhereUniqueInput
  ): Promise<AppLeague | null> {
    const result = await this.service.appLeague({
      where: params,
      select: {
        createdAt: true,
        id: true,
        isSelected: true,
        joinCode: true,
        leagueCode: true,
        leagueName: true,
        members: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AppLeague })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAppLeague(
    @common.Param() params: AppLeagueWhereUniqueInput,
    @common.Body() data: AppLeagueUpdateInput
  ): Promise<AppLeague | null> {
    try {
      return await this.service.updateAppLeague({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          isSelected: true,
          joinCode: true,
          leagueCode: true,
          leagueName: true,
          members: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AppLeague })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAppLeague(
    @common.Param() params: AppLeagueWhereUniqueInput
  ): Promise<AppLeague | null> {
    try {
      return await this.service.deleteAppLeague({
        where: params,
        select: {
          createdAt: true,
          id: true,
          isSelected: true,
          joinCode: true,
          leagueCode: true,
          leagueName: true,
          members: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/appRounds")
  @ApiNestedQuery(AppRoundFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AppRound",
    action: "read",
    possession: "any",
  })
  async findAppRounds(
    @common.Req() request: Request,
    @common.Param() params: AppLeagueWhereUniqueInput
  ): Promise<AppRound[]> {
    const query = plainToClass(AppRoundFindManyArgs, request.query);
    const results = await this.service.findAppRounds(params.id, {
      ...query,
      select: {
        appLeague: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        isFinished: true,
        roundNumber: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/appRounds")
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "update",
    possession: "any",
  })
  async connectAppRounds(
    @common.Param() params: AppLeagueWhereUniqueInput,
    @common.Body() body: AppRoundWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appRounds: {
        connect: body,
      },
    };
    await this.service.updateAppLeague({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/appRounds")
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "update",
    possession: "any",
  })
  async updateAppRounds(
    @common.Param() params: AppLeagueWhereUniqueInput,
    @common.Body() body: AppRoundWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appRounds: {
        set: body,
      },
    };
    await this.service.updateAppLeague({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/appRounds")
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "update",
    possession: "any",
  })
  async disconnectAppRounds(
    @common.Param() params: AppLeagueWhereUniqueInput,
    @common.Body() body: AppRoundWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appRounds: {
        disconnect: body,
      },
    };
    await this.service.updateAppLeague({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/rounds")
  @ApiNestedQuery(RoundFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Round",
    action: "read",
    possession: "any",
  })
  async findRounds(
    @common.Req() request: Request,
    @common.Param() params: AppLeagueWhereUniqueInput
  ): Promise<Round[]> {
    const query = plainToClass(RoundFindManyArgs, request.query);
    const results = await this.service.findRounds(params.id, {
      ...query,
      select: {
        appLeague: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/rounds")
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "update",
    possession: "any",
  })
  async connectRounds(
    @common.Param() params: AppLeagueWhereUniqueInput,
    @common.Body() body: RoundWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rounds: {
        connect: body,
      },
    };
    await this.service.updateAppLeague({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/rounds")
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "update",
    possession: "any",
  })
  async updateRounds(
    @common.Param() params: AppLeagueWhereUniqueInput,
    @common.Body() body: RoundWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rounds: {
        set: body,
      },
    };
    await this.service.updateAppLeague({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/rounds")
  @nestAccessControl.UseRoles({
    resource: "AppLeague",
    action: "update",
    possession: "any",
  })
  async disconnectRounds(
    @common.Param() params: AppLeagueWhereUniqueInput,
    @common.Body() body: RoundWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      rounds: {
        disconnect: body,
      },
    };
    await this.service.updateAppLeague({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/leagues/:id/users")
  @swagger.ApiOkResponse({
    type: AppUserDto,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetAllUsersInLeague(
    @common.Body()
    body: string
  ): Promise<AppUserDto[]> {
    return this.service.GetAllUsersInLeague(body);
  }

  @common.Get("/:id/get-users-in-league")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetUsersInLeague(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.GetUsersInLeague(body);
  }
}
