/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppLeagueWhereUniqueInput } from "../../appLeague/base/AppLeagueWhereUniqueInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";
import { AppMatchListRelationFilter } from "../../appMatch/base/AppMatchListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { MatchListRelationFilter } from "../../match/base/MatchListRelationFilter";
import { IntNullableFilter } from "../../util/IntNullableFilter";

@InputType()
class AppRoundWhereInput {
  @ApiProperty({
    required: false,
    type: () => AppLeagueWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AppLeagueWhereUniqueInput)
  @IsOptional()
  @Field(() => AppLeagueWhereUniqueInput, {
    nullable: true,
  })
  appLeague?: AppLeagueWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => AppMatchListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AppMatchListRelationFilter)
  @IsOptional()
  @Field(() => AppMatchListRelationFilter, {
    nullable: true,
  })
  appMatches?: AppMatchListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isFinished?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: () => MatchListRelationFilter,
  })
  @ValidateNested()
  @Type(() => MatchListRelationFilter)
  @IsOptional()
  @Field(() => MatchListRelationFilter, {
    nullable: true,
  })
  matches?: MatchListRelationFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  roundNumber?: IntNullableFilter;
}

export { AppRoundWhereInput as AppRoundWhereInput };
